In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import math
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

In [2]:
data = pd.read_csv("alldata.csv")
df = pd.DataFrame(data)
df.head()

rms    mean  kurtosis         SD  skewness      rms2  mean2  \
0  67.275553  58.000 -1.028288  36.441734 -0.564492  8.202168  4.750   
1  71.092369  66.125  0.150601  27.910252 -0.847333  8.431629  3.375   
2  68.045022  62.125 -0.747352  29.676530 -0.414097  8.248941  4.500   
3  67.579583  61.500 -0.855149  29.947573 -0.347715  8.220680  4.250   
4  65.620119  60.000 -0.669361  28.405231 -0.396812  8.100625  5.125   

   kurtosis2       SD2  skewness2  Class  
0   0.723204  4.773438   1.268973      0  
1  -1.059797  2.386719   0.131636      0  
2   0.154260  4.174754   1.007503      0  
3  -0.082869  4.399675   0.907823      0  
4  -1.173776  5.383507   0.619500      0

In [4]:
#from imblearn.over_sampling import SMOTE
#oversample = SMOTE()
df_target = df['Class']
df.pop('Class')#not needed in training 
#df, df_target = oversample.fit_resample(df, df_target)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Class, Length: 150, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, df_target, test_size=0.20, random_state=20)

In [6]:
#Suport vector classifier
from sklearn.svm import LinearSVC
svclassifier = LinearSVC(C=0.005,dual=False)
svclassifier.fit(x_train, y_train)
y_pred = svclassifier.predict(x_test)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy :",accuracy_score(y_test, y_pred))

[[6 2 0]
 [4 7 0]
 [4 2 5]]
              precision    recall  f1-score   support

           0       0.43      0.75      0.55         8
           1       0.64      0.64      0.64        11
           2       1.00      0.45      0.62        11

    accuracy                           0.60        30
   macro avg       0.69      0.61      0.60        30
weighted avg       0.71      0.60      0.61        30

Accuracy : 0.6


In [8]:
#naive bayers gaussian classifier
from sklearn.naive_bayes import GaussianNB
nbclassifier = GaussianNB()
nbclassifier.fit(x_train, y_train)
y_prednb = nbclassifier.predict(x_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_prednb))
print(classification_report(y_test,y_prednb))
print("Accuracy :",accuracy_score(y_test, y_prednb))

[[6 1 1]
 [2 6 3]
 [2 1 8]]
              precision    recall  f1-score   support

           0       0.60      0.75      0.67         8
           1       0.75      0.55      0.63        11
           2       0.67      0.73      0.70        11

    accuracy                           0.67        30
   macro avg       0.67      0.67      0.66        30
weighted avg       0.68      0.67      0.66        30

Accuracy : 0.6666666666666666


### Logistic Regression

In [10]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
lrclassifier = LogisticRegression(random_state = 10, max_iter = 5000, class_weight = 'balanced')
lrclassifier.fit(x_train, y_train)
y_predlr = lrclassifier.predict(x_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_predlr))
print(classification_report(y_test,y_predlr))
print("Accuracy :",accuracy_score(y_test, y_predlr))

[[7 1 0]
 [2 7 2]
 [1 2 8]]
              precision    recall  f1-score   support

           0       0.70      0.88      0.78         8
           1       0.70      0.64      0.67        11
           2       0.80      0.73      0.76        11

    accuracy                           0.73        30
   macro avg       0.73      0.75      0.74        30
weighted avg       0.74      0.73      0.73        30

Accuracy : 0.7333333333333333


### SVC Kernel

In [12]:
# Fitting the classifier into the Training set
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 0)
classifier.fit(x_train,y_train)
y_predsvmk = classifier.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_predsvmk))
print(classification_report(y_test,y_predsvmk))
print("Accuracy :",accuracy_score(y_test, y_predsvmk))

[[8 0 0]
 [5 1 5]
 [3 0 8]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         8
           1       1.00      0.09      0.17        11
           2       0.62      0.73      0.67        11

    accuracy                           0.57        30
   macro avg       0.71      0.61      0.50        30
weighted avg       0.73      0.57      0.48        30

Accuracy : 0.5666666666666667


### Multi-layer perceptron 

In [14]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(4, 3), random_state=1, max_iter = 10000)
clf.fit(x_train,y_train)  
y_predmlp = classifier.predict(x_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_predmlp))
print(classification_report(y_test,y_predmlp))
print("Accuracy :",accuracy_score(y_test, y_predmlp))

[[8 0 0]
 [5 1 5]
 [3 0 8]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         8
           1       1.00      0.09      0.17        11
           2       0.62      0.73      0.67        11

    accuracy                           0.57        30
   macro avg       0.71      0.61      0.50        30
weighted avg       0.73      0.57      0.48        30

Accuracy : 0.5666666666666667
